"""add games_count for devs

Revision ID: bb2e72da2eba
Revises: 
Create Date: 2026-04-27 08:18:44.469559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2e72da2eba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_profile', schema=None) as batch_op:
        batch_op.drop_column('games_count')

    # ### end Alembic commands ###
